"""Ajout de la colonne created_at à la table user

Revision ID: 358c354b591f
Revises: 43a85e1bafc3
Create Date: 2024-09-13 12:47:41.201312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358c354b591f'
down_revision = '43a85e1bafc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_responded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'agent'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'agent'::character varying"))
        batch_op.drop_column('is_active')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_responded')

    # ### end Alembic commands ###
