"""Ajout des colonnes admin_name et admin_email

Revision ID: 43a85e1bafc3
Revises: 0ceeafd3b86c
Create Date: 2024-09-10 19:39:41.749144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a85e1bafc3'
down_revision = '0ceeafd3b86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('admin_email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('admin_email')
        batch_op.drop_column('admin_name')

    # ### end Alembic commands ###
