"""Ajout du champ name à TrashBin

Revision ID: 61f7be6d1f59
Revises: 358c354b591f
Create Date: 2024-09-13 23:07:35.077308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f7be6d1f59'
down_revision = '358c354b591f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trash_bins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trash_bins', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
